//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_DB.DB {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord()]
    public partial class tFirstTable : ActiveRecordBase<tFirstTable> {
        
        private int _iD_FirstTable;
        
        private string _modelProperty2;
        
        [PrimaryKey(PrimaryKeyType.Native, "ID_FirstTable", ColumnType="Int32")]
        public virtual int ID_FirstTable {
            get {
                return this._iD_FirstTable;
            }
            set {
                this._iD_FirstTable = value;
            }
        }
        
        [Property("ModelProperty2", ColumnType="String")]
        public virtual string ModelProperty2 {
            get {
                return this._modelProperty2;
            }
            set {
                this._modelProperty2 = value;
            }
        }
    }
    
    public class db_NEWHelper {
        
        public static Type[] GetTypes() {
            return new Type[] {
                    typeof(tFirstTable)};
        }
    }
}
