//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiveWriter_SQL_Server.db {
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Castle.ActiveRecord;
    
    
    [ActiveRecord()]
    public partial class ModelClass1 : ActiveRecordBase<ModelClass1> {
        
        private int _id;
        
        private string _name;
        
        private IList<ModelClass2> _modelClass2s;
        
        [PrimaryKey(PrimaryKeyType.Native, ColumnType="Int32")]
        public virtual int id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string Name {
            get {
                return this._name;
            }
            set {
                this._name = value;
            }
        }
        
        [HasMany(typeof(ModelClass2), ColumnKey="ModelClass1")]
        public virtual IList<ModelClass2> ModelClass2s {
            get {
                return this._modelClass2s;
            }
            set {
                this._modelClass2s = value;
            }
        }
    }
    
    [ActiveRecord()]
    public partial class ModelClass2 : ActiveRecordBase<ModelClass2> {
        
        private int _id;
        
        private string _modelProperty1;
        
        private ModelClass1 _modelClass1;
        
        [PrimaryKey(PrimaryKeyType.Native, ColumnType="Int32")]
        public virtual int id {
            get {
                return this._id;
            }
            set {
                this._id = value;
            }
        }
        
        [Property(ColumnType="String")]
        public virtual string ModelProperty1 {
            get {
                return this._modelProperty1;
            }
            set {
                this._modelProperty1 = value;
            }
        }
        
        [BelongsTo()]
        public virtual ModelClass1 ModelClass1 {
            get {
                return this._modelClass1;
            }
            set {
                this._modelClass1 = value;
            }
        }
    }
    
    public class MainDBHelper {
        
        public static Type[] GetTypes() {
            return new Type[] {
                    typeof(ModelClass1),
                    typeof(ModelClass2)};
        }
    }
}
